version: '3.7'

services:
  api:
    build:
      context: .
    image: inventory_api
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  
  inventory_db:
    image: postgres:16rc1-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:  # Use environment variables for db configuration
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
volumes:
  postgres_data:
  